apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: %%CLUSTER_NAME%%-data-volume-%%NUM%%
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /data/%%CLUSTER_NAME%%-data-volume-%%NUM%%/

