apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb-mms-server-%%CLUSTER_NAME%%
spec:
  serviceName: mongodb-service-%%CLUSTER_NAME%%
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb-mms-server-%%CLUSTER_NAME%%
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-mms-server
          image: centos 
          env:
            - name: MMS_BASE_URL
              valueFrom: 
                secretKeyRef:
                  name: k8s-mongodb-opsmanager-$CLUSTER_NAME
                  key: base-url
            - name: MMS_AGENT_APIKEY
              valueFrom: 
                secretKeyRef:
                  name: k8s-mongodb-opsmanager-$CLUSTER_NAME
                  key: agent-apikey
            - name: MMS_GROUP_ID
              valueFrom: 
                secretKeyRef:
                  name: k8s-mongodb-opsmanager-$CLUSTER_NAME
                  key: group-id
            - name: MMS_BOOTSTRAP_URL
              value: "https://raw.githubusercontent.com/jasonmimick/k8s-mongodb-opsmanager/master/install-automation-agent.sh" 
          command:
          - "curl"
          - "-OL"
          - "$(MMS_BOOTSTRAP_URL)"
          - "|"
          - "/bin/bash" 
          ports:
            - containerPort: 27000
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mongodb-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: %%DISK_SIZE%%

