apiVersion: v1
kind: Service
metadata:
  name: mongodb-mms-server-service-%%CLUSTER_NAME%%
  labels:
    name: mongo
spec:
  selector:
    app: mongodb-mms-server-%%CLUSTER_NAME%%
  ports:
  - port: 27000
    targetPort: 27000
  clusterIP: None

