apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-%%CLUSTER_NAME%%
  labels:
    name: mongodb-service-%%CLUSTER_NAME%%
spec:
  selector:
    app: mongodb-server-%%CLUSTER_NAME%%
    role: mongodb-server-%%CLUSTER_NAME%%
  ports:
  - port: 30036
    targetPort: 30036
#    nodePort: 30036
  clusterIP: None
#  type: NodePort

